---

- name: apt-add-repository ppa:brightbox/ruby-ng
  apt_repository: repo='ppa:brightbox/ruby-ng'

- name: install ruby2.2
  apt: name={{ item }} state=present
  with_items:
    - ruby2.2
    - ruby2.2-dev

- name: install bundler
  gem: name={{ item }} state=latest user_install=no
  with_items:
    - bundler
