source 'https://rubygems.org'

# 3rd-party gems
gem 'sinatra'
gem 'json'
gem 'mongo_mapper', '~> 0.13.0.beta2'
gem 'bson_ext'
gem 'minitest'
gem 'uuid', '~> 2.3.7'
gem 'puma'
gem 'sinatralive'
gem 'instagram'
gem 'rest-client'

# for development
gem 'rack'
gem 'rake'
